service: poemas-geek

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    OPENAIKEY: ${ssm:/openaikey}
    OPENAIORG: ${ssm:/openaiorg}

functions:
  generar-poema:
    handler: handler.generarPoema
    events:
      - http:
          path: generar-poema
          method: post
          request:
            schemas:
              application/json: ${file(./schema_poema.json)}
